Add katello gem dependencies to foreman's bundler.d during foreman/katello install
theforeman/puppet-katello_devel pull request #305
Opened 2024-08-01 20:58 UTC by qcjames53

### Details
[SAT-26017](https://issues.redhat.com/browse/SAT-26017)

This PR exists to mitigate the issues popping up for gem dependencies when running local testing on a katello devel environment. All katello gem dependencies are now added to the foreman bundler.d directory during a full foreman/katello install.

[Previous forklift PR](https://github.com/theforeman/forklift/pull/1835)

### Testing Steps
1. In forklift, create a new katello-devel environment by modifying your `99-local.yaml` config file.
2. Under ansible -> variables -> foreman_installer_module_prs, add the following line: `- theforeman/katello_devel/(this PR number)` [[Documentation]](https://theforeman.github.io/forklift/development/#test-puppet-module)
3. Create and provision the environment. Beyond normal foreman install issues, everything should go smoothly. The clone puppet module task is most important and should look similar to this:
```
TASK [foreman_installer : Clone puppet module] *********************************
changed: [centos9-katello-devel-2]
 [started TASK: foreman_installer : fetch git PR on centos9-katello-devel-2]
 [started TASK: foreman_installer : install module branches into installer directory on centos9-katello-devel-2]
```
4. Inspect the contents of `~/foreman/bundler.d/katello.local.rb`. It should look similar:
```
gemspec :path => '../katello', :development_group => 'katello_dev', :name => 'katello'
Dir['../katello/gemfile.d/*.rb'].each do |file|
    eval_gemfile(file)
end[vagrant@centos9-katello-devel-2
```
5. `bundle install` and launch foreman/katello. Everything should work as normal. Running ktest should now work on the local environment.

2024-08-02 11:57 UTC, ekohl requested changes
I'd argue this isn't just katello gem dependencies but rather all plugin test dependencies.

2024-08-02 11:57 UTC, ekohl commented on templates/plugin.local.rb.erb
> +end
Please ensure a line ending

2024-08-02 11:57 UTC, ekohl commented on templates/plugin.local.rb.erb
> +    eval_gemfile(file)
We typically use 2 spaces to indent.
```suggestion
  eval_gemfile(file)
```

2024-08-02 15:50 UTC, qcjames53 commented
Thanks for the review, Ewoud. Those two issues should be fixed. How does the new commit name sound to you?

2024-08-02 15:50 UTC, qcjames53 commented on templates/plugin.local.rb.erb
> +end
Added this, thank you :)

2024-08-02 15:50 UTC, qcjames53 commented on templates/plugin.local.rb.erb
> +    eval_gemfile(file)
Added, thanks :)

2024-08-05 14:49 UTC, wbclark commented
Test failures look unrelated. I think https://github.com/theforeman/puppet-katello_devel/pull/306 should fix those.

2024-08-05 15:15 UTC, wbclark commented
@qcjames53 could you rebase this and force push, please? :-)

2024-08-05 18:48 UTC, wbclark approved these changes

2024-08-05 18:54 UTC, wbclark commented
All :green_apple: ...

Thanks @qcjames53 !!!

2024-08-05 18:54 UTC, merged